#!/bin/bash

echo "🔧 Fixing CodeQL Action Deprecation in GitHub Workflows"
echo "======================================================"

echo "✅ Updated CodeQL Actions from v2 to v3 in:"
echo "   • .github/workflows/security.yml"
echo "   • .github/workflows/ci-cd.yml"
echo ""
echo "📋 Changes Made:"
echo "   • github/codeql-action/init@v2 → @v3"
echo "   • github/codeql-action/autobuild@v2 → @v3"
echo "   • github/codeql-action/analyze@v2 → @v3"
echo "   • github/codeql-action/upload-sarif@v2 → @v3"
echo ""
echo "🎯 This resolves the deprecation warning:"
echo "   'CodeQL Action major versions v1 and v2 have been deprecated'"
echo ""
echo "🚀 Your CI/CD pipeline should now run without deprecation warnings!"
echo ""
echo "To apply these changes to your GitHub repository:"
echo "1. Copy the updated workflow files"
echo "2. Commit and push the changes"
echo "3. All GitHub Actions will use the latest CodeQL Action v3"