name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: CI validation (TypeScript workaround)
      run: ./scripts/ci-build-workaround.sh
    
    - name: Build application
      run: npm run build
      env:
        DATABASE_URL: postgresql://test:test@localhost:5432/test
    
    - name: Basic security audit
      run: npm audit --audit-level moderate
      continue-on-error: true
    
    - name: Build success
      run: echo "✅ Build completed successfully!"